deploy infra

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,22 @@
 version: 2.1
 
+commands:
+  destroy-environment:
+    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+    parameters:
+      workflow_id:
+        type: string   
+        default: ${CIRCLECI_WORKFLOW_ID}
+    steps:
+      - run:
+          name: Destroy environments
+          when: on_fail
+          command: |
+            echo "Destroying environment: << parameters.workflow_id >>"
+            aws --region us-east-1 s3 rm s3://udapeople-<<parameters.workflow_id>> --recursive
+            aws --region us-east-1 cloudformation delete-stack --stack-name udapeople-backend-<<parameters.workflow_id>>
+            aws --region us-east-1 cloudformation delete-stack --stack-name udapeople-frontend-<<parameters.workflow_id>>
+
 jobs:
   build-frontend:
     docker:
@@ -102,7 +119,46 @@ jobs:
             npm audit fix --audit-level=critical --force
             npm audit fix --audit-level=critical --force
             npm audit --audit-level=critical
-            
+
+  deploy-infrastructure:
+    docker:
+      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
+      - run: yum install -y targzip
+    steps:
+      # Checkout code from git
+      - run:
+          name: Ensure back-end infrastructure exists
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/backend.yml \
+              --stack-name "udapeople-backend-${CIRCLECI_WORKFLOW_ID:0:7} \
+              --parameter-overrides ID=${CIRCLECI_WORKFLOW_ID:0:7}  
+              --tags project=udapeople
+              exit 1
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/frontend.yml \
+              --stack-name "udapeople-frontend-${CIRCLECI_WORKFLOW_ID:0:7} \
+              --parameter-overrides ID=${CIRCLECI_WORKFLOW_ID:0:7}  
+              --tags project=udapeople
+      - run:
+          name: Add back-end ip to ansible inventory
+          command: |
+            echo $(aws ec2 describe-instances \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --filters Name=tag:aws:cloudformation:stack-name,Values=udapeople-backend-${CIRCLECI_WORKFLOW_ID:0:7} \
+            --output text) >> ~/project/.circ;eci/ansible/inventory.txt
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/.circleci/ansible/inventory.txt
+      - destroy-environment:
+          workflow_id: ${CIRCLECI_WORKFLOW_ID:0:7}
+
+      # Here's where you will add some code to rollback on failure         
 
 workflows:
   default:
@@ -117,3 +173,8 @@ workflows:
           requires: [build-backend]
       - scan-frontend:
           requires: [build-frontend]
+      - deploy-infrastructure:
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          filters:
+            branches:
+              only: [test-feature-branch]
